// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ObjectData,
} from "./types";


export default __t.row({
  id: __t.string().primaryKey(),
  objectType: __t.string().name("object_type"),
  x: __t.i32(),
  y: __t.i32(),
  rotation: __t.i32(),
  scaleX: __t.f64().name("scale_x"),
  scaleY: __t.f64().name("scale_y"),
  width: __t.i32(),
  height: __t.i32(),
  get data() {
    return ObjectData;
  },
  createdBy: __t.identity().name("created_by"),
  createdAt: __t.timestamp().name("created_at"),
  expiresAt: __t.option(__t.timestamp()).name("expires_at"),
  ghostUntil: __t.option(__t.timestamp()).name("ghost_until"),
  keptForever: __t.bool().name("kept_forever"),
  protected: __t.bool(),
  revealed: __t.bool(),
  authorName: __t.option(__t.string()).name("author_name"),
  parentId: __t.option(__t.string()).name("parent_id"),
});
