// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  ObjectData,
} from "./types";

export default {
  id: __t.string(),
  objectType: __t.string(),
  x: __t.i32(),
  y: __t.i32(),
  rotation: __t.i32(),
  scaleX: __t.f64(),
  scaleY: __t.f64(),
  width: __t.i32(),
  height: __t.i32(),
  get data() {
    return ObjectData;
  },
  parentId: __t.option(__t.string()),
  ttlMicros: __t.u64(),
};
