// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const CanvasObject = __t.object("CanvasObject", {
  id: __t.string(),
  objectType: __t.string(),
  x: __t.i32(),
  y: __t.i32(),
  rotation: __t.i32(),
  scaleX: __t.f64(),
  scaleY: __t.f64(),
  width: __t.i32(),
  height: __t.i32(),
  get data() {
    return ObjectData;
  },
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  expiresAt: __t.option(__t.timestamp()),
  ghostUntil: __t.option(__t.timestamp()),
  keptForever: __t.bool(),
  protected: __t.bool(),
  revealed: __t.bool(),
  authorName: __t.option(__t.string()),
  parentId: __t.option(__t.string()),
  hidden: __t.bool(),
});
export type CanvasObject = __Infer<typeof CanvasObject>;

export const Comment = __t.object("Comment", {
  id: __t.u64(),
  objectId: __t.string(),
  userIdentity: __t.identity(),
  text: __t.string(),
  createdAt: __t.timestamp(),
  hidden: __t.bool(),
});
export type Comment = __Infer<typeof Comment>;

export const Cursor = __t.object("Cursor", {
  identity: __t.identity(),
  x: __t.i32(),
  y: __t.i32(),
  updatedAt: __t.timestamp(),
});
export type Cursor = __Infer<typeof Cursor>;

export const ObjectData = __t.object("ObjectData", {
  pathData: __t.option(__t.string()),
  color: __t.option(__t.string()),
  strokeWidth: __t.option(__t.f64()),
  text: __t.option(__t.string()),
  fontSize: __t.option(__t.f64()),
  emoji: __t.option(__t.string()),
  size: __t.option(__t.f64()),
  secret: __t.option(__t.string()),
  unlockedAt: __t.option(__t.f64()),
  radius: __t.option(__t.f64()),
  locked: __t.option(__t.bool()),
  rotation: __t.option(__t.f64()),
  src: __t.option(__t.string()),
  width: __t.option(__t.f64()),
  height: __t.option(__t.f64()),
  shapeType: __t.option(__t.string()),
  serializer: __t.option(__t.string()),
});
export type ObjectData = __Infer<typeof ObjectData>;

export const ObjectExpiry = __t.object("ObjectExpiry", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  objectId: __t.string(),
});
export type ObjectExpiry = __Infer<typeof ObjectExpiry>;

export const ObjectHistory = __t.object("ObjectHistory", {
  id: __t.u64(),
  objectId: __t.string(),
  userIdentity: __t.identity(),
  action: __t.string(),
  createdAt: __t.timestamp(),
});
export type ObjectHistory = __Infer<typeof ObjectHistory>;

export const ObjectPatch = __t.object("ObjectPatch", {
  x: __t.option(__t.i32()),
  y: __t.option(__t.i32()),
  rotation: __t.option(__t.i32()),
  scaleX: __t.option(__t.f64()),
  scaleY: __t.option(__t.f64()),
  width: __t.option(__t.i32()),
  height: __t.option(__t.i32()),
  get data() {
    return __t.option(ObjectData);
  },
  revealed: __t.option(__t.bool()),
  keptForever: __t.option(__t.bool()),
  parentId: __t.option(__t.string()),
});
export type ObjectPatch = __Infer<typeof ObjectPatch>;

export const Reaction = __t.object("Reaction", {
  id: __t.u64(),
  objectId: __t.string(),
  userIdentity: __t.identity(),
  reactionType: __t.string(),
  createdAt: __t.timestamp(),
});
export type Reaction = __Infer<typeof Reaction>;

export const SeedPayload = __t.object("SeedPayload", {
  id: __t.string(),
  objectType: __t.string(),
  x: __t.i32(),
  y: __t.i32(),
  rotation: __t.i32(),
  scaleX: __t.f64(),
  scaleY: __t.f64(),
  width: __t.i32(),
  height: __t.i32(),
  get data() {
    return ObjectData;
  },
  authorName: __t.option(__t.string()),
  parentId: __t.option(__t.string()),
  protected: __t.bool(),
  ttlMicros: __t.u64(),
  ageMicros: __t.u64(),
});
export type SeedPayload = __Infer<typeof SeedPayload>;

export const SeedState = __t.object("SeedState", {
  id: __t.u32(),
  seeded: __t.bool(),
});
export type SeedState = __Infer<typeof SeedState>;

export const User = __t.object("User", {
  identity: __t.identity(),
  username: __t.string(),
  avatar: __t.string(),
  bio: __t.string(),
  createdAt: __t.timestamp(),
  lastSeen: __t.timestamp(),
  online: __t.bool(),
  homeX: __t.option(__t.i32()),
  homeY: __t.option(__t.i32()),
});
export type User = __Infer<typeof User>;

export const WallStats = __t.object("WallStats", {
  id: __t.u32(),
  totalExpired: __t.u64(),
  currentCount: __t.u64(),
  keptForeverCount: __t.u64(),
});
export type WallStats = __Infer<typeof WallStats>;

