// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddCommentReducer from "../add_comment_reducer";
import AddReactionReducer from "../add_reaction_reducer";
import CreateObjectReducer from "../create_object_reducer";
import DeleteObjectReducer from "../delete_object_reducer";
import DrawOverReducer from "../draw_over_reducer";
import HideCommentReducer from "../hide_comment_reducer";
import HideObjectReducer from "../hide_object_reducer";
import RecomputeWallStatsReducer from "../recompute_wall_stats_reducer";
import RemoveReactionReducer from "../remove_reaction_reducer";
import SeedConfessionsReducer from "../seed_confessions_reducer";
import SeedObjectsReducer from "../seed_objects_reducer";
import SetHomeReducer from "../set_home_reducer";
import SetUsernameReducer from "../set_username_reducer";
import UpdateCursorReducer from "../update_cursor_reducer";
import UpdateObjectReducer from "../update_object_reducer";

export type AddCommentParams = __Infer<typeof AddCommentReducer>;
export type AddReactionParams = __Infer<typeof AddReactionReducer>;
export type CreateObjectParams = __Infer<typeof CreateObjectReducer>;
export type DeleteObjectParams = __Infer<typeof DeleteObjectReducer>;
export type DrawOverParams = __Infer<typeof DrawOverReducer>;
export type HideCommentParams = __Infer<typeof HideCommentReducer>;
export type HideObjectParams = __Infer<typeof HideObjectReducer>;
export type RecomputeWallStatsParams = __Infer<typeof RecomputeWallStatsReducer>;
export type RemoveReactionParams = __Infer<typeof RemoveReactionReducer>;
export type SeedConfessionsParams = __Infer<typeof SeedConfessionsReducer>;
export type SeedObjectsParams = __Infer<typeof SeedObjectsReducer>;
export type SetHomeParams = __Infer<typeof SetHomeReducer>;
export type SetUsernameParams = __Infer<typeof SetUsernameReducer>;
export type UpdateCursorParams = __Infer<typeof UpdateCursorReducer>;
export type UpdateObjectParams = __Infer<typeof UpdateObjectReducer>;

